# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 521)
        MainWindow.setWindowTitle("MainWindow")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.main_tab.setFont(font)
        self.main_tab.setObjectName("main_tab")
        self.download_tab = QtWidgets.QWidget()
        self.download_tab.setObjectName("download_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.download_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.download_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.url_input = QtWidgets.QLineEdit(self.download_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_input.sizePolicy().hasHeightForWidth())
        self.url_input.setSizePolicy(sizePolicy)
        self.url_input.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.url_input.setFont(font)
        self.url_input.setText("")
        self.url_input.setAlignment(QtCore.Qt.AlignCenter)
        self.url_input.setObjectName("url_input")
        self.horizontalLayout.addWidget(self.url_input)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(168, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.download_button = QtWidgets.QPushButton(self.download_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download_button.sizePolicy().hasHeightForWidth())
        self.download_button.setSizePolicy(sizePolicy)
        self.download_button.setMinimumSize(QtCore.QSize(120, 40))
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_2.addWidget(self.download_button)
        spacerItem1 = QtWidgets.QSpacerItem(168, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.download_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.list_supported = QtWidgets.QListWidget(self.download_tab)
        self.list_supported.setObjectName("list_supported")
        self.verticalLayout_2.addWidget(self.list_supported)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(188, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.quit_button = QtWidgets.QPushButton(self.download_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_button.sizePolicy().hasHeightForWidth())
        self.quit_button.setSizePolicy(sizePolicy)
        self.quit_button.setMinimumSize(QtCore.QSize(50, 32))
        self.quit_button.setObjectName("quit_button")
        self.gridLayout.addWidget(self.quit_button, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.main_tab.addTab(self.download_tab, "")
        self.merge_tab = QtWidgets.QWidget()
        self.merge_tab.setObjectName("merge_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.merge_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.merge_tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(240, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.merge_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.merge_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.files_button = QtWidgets.QPushButton(self.merge_tab)
        self.files_button.setObjectName("files_button")
        self.gridLayout_8.addWidget(self.files_button, 0, 0, 1, 1)
        self.folder_button = QtWidgets.QPushButton(self.merge_tab)
        self.folder_button.setObjectName("folder_button")
        self.gridLayout_8.addWidget(self.folder_button, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.merge_tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem6, 2, 1, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.merge_tab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 3, 0, 1, 1)
        self.main_tab.addTab(self.merge_tab, "")
        self.gridLayout_9.addWidget(self.main_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("MainWindow", "LINK CHAP"))
        self.download_button.setText(_translate("MainWindow", "DOWNLOAD"))
        self.label_4.setText(_translate("MainWindow", "DANH SÁCH CÁC WEB HỖ TRỢ"))
        self.quit_button.setText(_translate("MainWindow", "QUIT"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.download_tab), _translate("MainWindow", "Tải raw"))
        self.label.setText(_translate("MainWindow", "Các lưu ý:"))
        self.label_3.setText(_translate("MainWindow", "Ghép raw theo thứ tự bảng chữ cái tự nhiên (..,0,1,2....,A,B,C..a,b,c,...)"))
        self.label_5.setText(_translate("MainWindow", "Nếu chiều ngang những hình ảnh không giống nhau thì lấy chiều ngang lớn nhất"))
        self.files_button.setText(_translate("MainWindow", "Chọn hình ảnh"))
        self.folder_button.setText(_translate("MainWindow", "Chọn thư mục"))
        self.label_6.setText(_translate("MainWindow", "* Nếu ghép quá nhiều ảnh có thể dẫn đến tình trạng không phản hồi."))
        self.label_7.setText(_translate("MainWindow", "**Tải raw có thể không tải đầy đủ một vài ảnh. Thử lại hoặc tải thủ công"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.merge_tab), _translate("MainWindow", "Ghép raw"))

